config/routes.rb
Rails.application.routes.draw do
  get 'sessions/index'

  get 'log_in' => 'sessions#index', :as => 'log_in'
  get "log_out" => "sessions#destroy", :as => "log_out"

  resources :sessions

  get 'sign_up' => 'users#new', :as => 'sign_up'
  root :to => 'users#new'
  resources :users
  match '/index', to: 'tasks#index', via: 'get'
  #root 'tasks#index'
  resources :tasks do
    get "delete"

  end

end

app/models/project.rb
class Task < ActiveRecord::Base

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password

  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email, :password
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      return nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


def new
end

def create
  params.permit!
  user = User.authenticate(params[:email], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to tasks_url :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
  end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

   before_action :all_tasks, only: [:index, :create, :update, :destroy]
   before_action :set_tasks, only: [:edit, :update, :destroy]


  def index
    if session[:user_id] == nil
      redirect_to root_url, :notice => "Need to log in!"
    else
      @task = Task.new
      respond_to do |format|
        format.html
        format.json
      end
    end
  end

  def new
    @task = Task.new
  end

  def create
    params.permit!
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'task was successfully created.' }
        format.js   {}
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "create" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    params.permit!
    @task.update(params[:task])
  end

  def destroy
    @task.destroy
  end


private

   def set_tasks
      @task = Task.find(params[:id])
   end

   def all_tasks
      @tasks = Task.all
   end



  def task_params
    params.require(:task).permit(:id, :deadline)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    params.permit!
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => 'Signed up'
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <h3>
   (c) Artem Batiyevsky
  </h3>

</footer>

app/views/layouts/_header.html.erb
<div class="center hero-unit">
  <h1>SIMPLE TODO LISTS</h1>

  <h2> FROM RUBY GARAGE </h2>


  <nav id="user_nav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
    <% if current_user %>
        <p class="navbar-text">Signed in as  <%= current_user.email %>

        <%= link_to "Log out", log_out_path, {class: "btn btn-default navbar-btn"}%></p>
    <% else %>
            <%= link_to "Sign up", sign_up_path, {class: "btn btn-default navbar-btn"} %>
        <%= link_to "Log in", log_in_path, {class: "btn btn-default navbar-btn"} %>
    <% end %>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- JS dependencies -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="/assets/bootstrap.min.js"></script>

<!-- bootbox code -->
<script src="/assets/bootbox.min.js"></script>
  <%= render 'layouts/header' %>



<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash#{name}" %>
  <% end %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task, remote: true do |f| %>
  <%= f.text_field :task %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/_task.html.erb
<li class="list-group-item"><%= task.task %>
  <%= link_to edit_task_path(task), remote: true do%>
        <button>Edit</button>
  <% end %>
  <%= link_to task, remote: true, method: :delete, data: { confirm: 'Are you sure?' } do %>
  <button>Delete!</button>
<% end %>

  </li>

app/views/tasks/create.js.erb
/**
 * Created by artemiy on 3/14/16.
 */
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideUp(350);

app/views/tasks/destroy.js.erb
$('#tasks').html("<%= j (render @tasks) %>");

app/views/tasks/edit.js.erb
/**
 * Created by artemiy on 3/14/16.
 */
$('#tasks').html("<%= j (render 'form') %>");
$('#task-form').slideUp(350);

app/views/tasks/index.html.erb
<div class="row">



<ul class="list-group" id="tasks">
  <li class="list-group-item"></li>

<% for task in @tasks %>

      <li class="list-group-item"><%= task.task %>
        <%= link_to edit_task_path(task), method: :update, remote: true do %>
        <button>Edit</button>
            <%end%>
        <%= link_to task, remote: true, method: :delete, data: { confirm: 'Are you sure?' } do %>
  <button>Delete!</button>
            <% end %>
    </li>
  <% end %>
</ul>
<center>
<%= link_to new_task_path, remote: true do %>
    <button>New task</button>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-2" id="task-form" style="display:none;"></div>
</div>
  </center>

app/views/tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

app/views/tasks/update.js.erb
/**
 * Created by artemiy on 3/14/16.
 */
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideUp(350);

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button btn-default"><%= f.submit %></p>
<% end %>